name: Java CI with Maven
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql user: ironhack
          mysql root password: ironhack2024          

      - run: mysql -h 172.17.0.1 --port 3306 -u ironhack -p ironhack2024 -e 'CREATE DATABASE IF NOT EXISTS iron-hack-test;'
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
